In [52]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

## Question 1 ##
### what version is Pandas installed ###

In [6]:
pd.__version__

'2.1.0'

## Question 2 ##
### How many columns are in the dataset? ###

In [3]:
housing_df = pd.read_csv("../../data/housing.csv")

In [7]:
print(f'There are {housing_df.shape[1]} columns')


There are 10 columns


In [8]:
housing_df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

## Question 3 ##
### Which columns in the dataset have missing values? ###

In [13]:
print(f'''The '{housing_df.columns[housing_df.isna().any()][0]}' column has missing values''')

The 'total_bedrooms' column has missing values


## Question 4 ##
### How many unique values does the ocean_proximity column have? ###

In [19]:
housing_df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [17]:
print(f'''There are '{len(housing_df['ocean_proximity'].unique())}' unique values in the column 'ocean_proximity' ''')

There are '5' unique values in the column 'ocean_proximity' 


## Question 5 ##
### What's the average value of the median_house_value for the houses located near the bay? ###

In [31]:
print(f''' ${np.average(housing_df['median_house_value'][housing_df['ocean_proximity'] == 'NEAR BAY']) :,.2f} ''')

 $259,212.31 


## Question 6 ##
### ###
1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

Hint: take into account only 3 digits after the decimal point.
Yes
No 
### ###

In [4]:
np.mean(housing_df['total_bedrooms'].apply(lambda x: pd.to_numeric(x, errors='coerce')))

537.8705525375618

In [12]:
print(f'''The 'total_bedrooms' sq ft average is {housing_df['total_bedrooms'].mean(axis=0, skipna=True)},
taking in consideration of the missing values''')

The 'total_bedrooms' average is 537.8705525375618,
taking in consideration of the missing values


In [14]:
print(f'''The 'total_bedrooms' sq ft average with the missing value filled with the average previously is 
{housing_df['total_bedrooms'].fillna(housing_df['total_bedrooms'].mean(axis=0, skipna=True)).mean()}. 
The average did not change with or without the missing values being fill.''')

The 'total_bedrooms' sq ft average with the missing value filled with the average previously is 
537.8705525375617. 
The average did not change with or without the missing values being fill.


## Question 7 ##
### ###
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

   
Note: You just implemented linear regression. We'll talk about it in the next lesson.
-1.4812
0.001
5.6992
23.1233
 ### ###

In [35]:
housing_df[['housing_median_age','total_rooms','total_bedrooms']][housing_df['ocean_proximity'] == 'ISLAND']

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [36]:
X = housing_df[['housing_median_age','total_rooms','total_bedrooms']][housing_df['ocean_proximity'] == 'ISLAND'].to_numpy()

In [55]:
XT = X.transpose()

In [58]:
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [59]:
XTX = np.dot(XT,X)

In [42]:
y = np.array([950, 1300, 800, 1000, 1300])

In [43]:
y

array([ 950, 1300,  800, 1000, 1300])

In [60]:
XTX_inverse = np.linalg.inv(XTX)

In [65]:
a = np.dot(XTX_inverse, XT)

In [68]:
w = np.dot(a, y)

array([23.12330961, -1.48124183,  5.69922946])